(() => {
  "use strict";

  const topicMeta = [
    ["A.1 Kinematics","A. Space, time and motion","SL"],["A.2 Forces and momentum","A. Space, time and motion","SL"],["A.3 Work, energy and power","A. Space, time and motion","SL"],["A.4 Rigid body mechanics","A. Space, time and motion","HL"],["A.5 Galilean and special relativity","A. Space, time and motion","HL"],
    ["B.1 Thermal energy transfers","B. The particulate nature of matter","SL"],["B.2 Greenhouse effect","B. The particulate nature of matter","SL"],["B.3 Gas laws","B. The particulate nature of matter","SL"],["B.4 Thermodynamics","B. The particulate nature of matter","HL"],["B.5 Current and circuits","B. The particulate nature of matter","SL"],
    ["C.1 Simple harmonic motion","C. Wave behaviour","SL"],["C.2 Wave model","C. Wave behaviour","SL"],["C.3 Wave phenomena","C. Wave behaviour","SL"],["C.4 Standing waves and resonance","C. Wave behaviour","SL"],["C.5 Doppler effect","C. Wave behaviour","SL"],
    ["D.1 Gravitational fields","D. Fields","SL"],["D.2 Electric and magnetic fields","D. Fields","SL"],["D.3 Motion in electromagnetic fields","D. Fields","SL"],["D.4 Induction","D. Fields","HL"],
    ["E.1 Structure of the atom","E. Nuclear and quantum physics","SL"],["E.2 Quantum physics","E. Nuclear and quantum physics","HL"],["E.3 Radioactive decay","E. Nuclear and quantum physics","SL"],["E.4 Fission","E. Nuclear and quantum physics","SL"],["E.5 Fusion and stars","E. Nuclear and quantum physics","SL"],
    ["Skills in physics","Tools and inquiry","SL"]
  ].map(([name,theme,minimumLevel],i)=>({name,theme,minimumLevel,icon:name.slice(0,1),colour:["#7656c8","#d97925","#168eb2","#2c9b69","#b04475","#52657a"][Math.floor(i/5)]||"#52657a"}));

  const questions=[]; let n=0;
  const add=(topic,level,q,a)=>questions.push({id:`ib-${String(++n).padStart(4,"0")}`,topic,level,subtopic:topic,question:q,answer:a});
  const many=(topic,level,pairs)=>pairs.forEach(([q,a])=>add(topic,level,q,a));
  const f=x=>Number(x.toFixed(3)).toString();

  many("A.1 Kinematics","SL",[
    ["Distinguish distance from displacement.","Distance is total path length; displacement is the directed change in position."],["Distinguish speed from velocity.","Velocity is speed in a stated direction; speed is scalar."],["Define acceleration.","Rate of change of velocity: a = Δv/Δt."],["What does the gradient of a displacement-time graph represent?","Velocity."],["What does the gradient of a velocity-time graph represent?","Acceleration."],["What does the area under a velocity-time graph represent?","Displacement."],["State the constant-acceleration equation that does not contain time.","v² = u² + 2as."],["At the highest point of a vertical throw, what are the velocity and acceleration?","Velocity is zero instantaneously; acceleration is g downward."],["What assumption defines projectile motion without air resistance?","The only force after launch is weight, so horizontal velocity is constant and vertical acceleration is g."],["When is average speed equal to the magnitude of average velocity?","When motion is along a straight line without reversing direction."],
  ]);
  [[0,12,3],[5,21,4],[18,2,8],[10,30,5],[25,5,4]].forEach(([u,v,t])=>add("A.1 Kinematics","SL",`An object changes velocity from ${u} m s⁻¹ to ${v} m s⁻¹ in ${t} s. Calculate its acceleration.`,`a = (v-u)/t = ${f((v-u)/t)} m s⁻².`));

  many("A.2 Forces and momentum","SL",[
    ["State Newton's first law.","An object remains at rest or at constant velocity unless acted on by a resultant external force."],["State Newton's second law in momentum form.","Resultant force equals rate of change of momentum: F = Δp/Δt."],["State Newton's third law.","When two bodies interact, they exert equal and opposite forces on each other."],["Define linear momentum.","p = mv; mass multiplied by velocity."],["State the condition for momentum conservation.","The resultant external force on the system is zero."],["Define impulse.","Change in momentum; J = FΔt = Δp."],["Why does an airbag reduce injury?","It increases stopping time, reducing the average force for the same change in momentum."],["What is terminal speed?","Constant speed reached when resistive force equals the driving force or weight."],["What does the area under a force-time graph represent?","Impulse or change in momentum."],["Distinguish mass from weight.","Mass measures inertia in kg; weight is gravitational force W = mg in N."],
  ]);
  [[2,3],[5,8],[0.4,25],[1200,12],[65,7]].forEach(([m,v])=>add("A.2 Forces and momentum","SL",`Calculate the momentum of a ${m} kg object moving at ${v} m s⁻¹.`,`p = mv = ${f(m*v)} kg m s⁻¹.`));

  many("A.3 Work, energy and power","SL",[
    ["Define work done by a constant force.","Energy transferred by a force: W = Fs cos θ."],["Define power.","Rate of energy transfer or work done: P = ΔE/Δt."],["State the translational kinetic energy equation.","Eₖ = ½mv²."],["State the change in gravitational potential energy near Earth's surface.","ΔEₚ = mgΔh."],["State the elastic potential energy of a Hookean spring.","Eₑ = ½k(Δx)²."],["What does the area under a force-displacement graph represent?","Work done."],["Define efficiency.","Useful output energy or power divided by total input energy or power."],["State the principle of conservation of energy.","Total energy of an isolated system remains constant, although it may change form."],["When does a force do no work?","When displacement is zero or perpendicular to the force."],["Why does braking distance rise strongly with speed?","Kinetic energy is proportional to speed squared."],
  ]);
  [[2,4],[5,10],[1200,20],[0.25,8],[70,6]].forEach(([m,v])=>add("A.3 Work, energy and power","SL",`Calculate the kinetic energy of a ${m} kg object moving at ${v} m s⁻¹.`,`Eₖ = ½mv² = ${f(.5*m*v*v)} J.`));

  many("A.4 Rigid body mechanics","HL",[
    ["Define torque about an axis.","τ = rF sin θ, the turning effect of a force."],["State the conditions for static equilibrium.","Resultant force is zero and resultant torque about any axis is zero."],["Define angular velocity.","Rate of change of angular displacement: ω = Δθ/Δt."],["Relate linear speed to angular speed.","v = rω."],["Define moment of inertia.","Rotational inertia: I = Σmr² for point masses."],["State rotational kinetic energy.","Eᵣ = ½Iω²."],["State the rotational form of Newton's second law.","τ = Iα."],["Define angular momentum of a rigid body.","L = Iω."],["When is angular momentum conserved?","When resultant external torque is zero."],["Why does a skater spin faster when pulling in their arms?","Moment of inertia falls, so ω rises to conserve angular momentum."],
  ]);
  [[2,5],[0.4,12],[3,1.5],[0.2,30],[5,0.8]].forEach(([r,F])=>add("A.4 Rigid body mechanics","HL",`A perpendicular force of ${F} N acts ${r} m from an axis. Calculate the torque.`,`τ = rF = ${f(r*F)} N m.`));

  many("A.5 Galilean and special relativity","HL",[
    ["State the Galilean transformation for position.","x' = x - vt for frames in relative motion along x."],["What is invariant in Galilean relativity?","Time and acceleration."],["State Einstein's first postulate.","The laws of physics are the same in all inertial reference frames."],["State Einstein's second postulate.","The speed of light in vacuum is the same for all inertial observers."],["Define proper time.","Time between two events measured in the frame where they occur at the same position."],["State the Lorentz factor.","γ = 1/√(1-v²/c²)."],["State the time dilation relation.","Δt = γΔt₀."],["Define proper length.","Length measured in the rest frame of the object."],["State the length contraction relation.","L = L₀/γ."],["Why can no massive object reach c?","The energy required grows without limit as v approaches c."],
  ]);

  many("B.1 Thermal energy transfers","SL",[
    ["Define temperature microscopically.","A measure related to the average random kinetic energy of particles."],["Define internal energy.","The total microscopic kinetic and intermolecular potential energy of a system."],["Define specific heat capacity.","Energy required per unit mass to raise temperature by 1 K: c = Q/(mΔT)."],["Define specific latent heat.","Energy required per unit mass for a phase change at constant temperature: L = Q/m."],["Why is temperature constant during a phase change?","Transferred energy changes intermolecular potential energy rather than average kinetic energy."],["Describe conduction in a solid.","Energy transfers through particle interactions; mobile electrons also contribute in metals."],["Describe convection.","Bulk motion of a fluid caused by density differences transfers energy."],["State the Stefan-Boltzmann law.","P = eσAT⁴ for radiated power."],["What is a black body?","An ideal absorber and emitter of radiation at all wavelengths."],["State Wien's displacement law.","λmax T = constant."],
  ]);
  [[1,4200,5],[2,900,20],[0.5,390,30],[3,450,12],[0.25,2100,8]].forEach(([m,c,dT])=>add("B.1 Thermal energy transfers","SL",`Calculate the energy needed to heat ${m} kg of a material with c = ${c} J kg⁻¹ K⁻¹ through ${dT} K.`,`Q = mcΔT = ${f(m*c*dT)} J.`));

  many("B.2 Greenhouse effect","SL",[
    ["What is the greenhouse effect?","Atmospheric gases absorb and re-emit outgoing infrared radiation, warming the surface and lower atmosphere."],["Name two important greenhouse gases.","For example carbon dioxide, water vapour or methane."],["Why does incoming solar radiation pass through the atmosphere more readily than outgoing terrestrial radiation?","They have different wavelength distributions; greenhouse gases absorb much of Earth's infrared."],["What is albedo?","The fraction of incident radiation reflected by a surface."],["How does melting ice create positive feedback?","Lower albedo increases absorption and warming, causing more melting."],["What is Earth's energy balance condition?","Average absorbed solar power equals average emitted infrared power."],["Why is Earth's emitted radiation mainly infrared?","Earth is much cooler than the Sun, so Wien's law gives a longer peak wavelength."],["Distinguish the natural and enhanced greenhouse effects.","The natural effect makes Earth habitable; the enhanced effect is extra warming from increased greenhouse gas concentrations."],["How can volcanic aerosols temporarily cool Earth?","They increase reflection of incoming solar radiation."],["Why are climate models tested against past data?","To assess how reliably they reproduce observed climate behaviour."],
  ]);

  many("B.3 Gas laws","SL",[
    ["State the ideal-gas equation.","pV = nRT = NkBT."],["What is absolute temperature?","Temperature measured from absolute zero in kelvin."],["Convert Celsius temperature to kelvin.","T/K = θ/°C + 273.15."],["State Boyle's law conditions and relation.","For fixed gas amount at constant temperature, pV = constant."],["State Charles's law conditions and relation.","For fixed gas amount at constant pressure, V/T = constant."],["What causes gas pressure microscopically?","Particle collisions with container walls change momentum and exert force."],["How does increasing temperature at fixed volume affect pressure?","Particles move faster and transfer momentum more frequently, so pressure rises."],["State the mean translational kinetic energy of an ideal-gas molecule.","Average Eₖ = 3kBT/2."],["Name two ideal-gas assumptions.","Particles have negligible volume and no intermolecular forces except during elastic collisions."],["Why must gas-law temperatures be in kelvin?","The proportionalities use absolute temperature measured from zero thermal kinetic energy."],
  ]);
  [[1,1e5,0.024],[2,2e5,0.01],[0.5,1.5e5,0.02]].forEach(([n,p,V])=>add("B.3 Gas laws","SL",`For ${n} mol of ideal gas at pressure ${p} Pa and volume ${V} m³, calculate T using R = 8.31 J mol⁻¹ K⁻¹.`,`T = pV/nR = ${f(p*V/(n*8.31))} K.`));

  many("B.4 Thermodynamics","HL",[
    ["State the first law of thermodynamics using work done by the gas.","ΔU = Q - W."],["What is an isothermal process?","A process at constant temperature; for an ideal gas ΔU = 0."],["What is an adiabatic process?","A process with no thermal energy transfer: Q = 0."],["What is an isobaric process?","A process at constant pressure."],["What is an isochoric process?","A process at constant volume, so W = 0."],["What does area under a p-V graph represent?","Work done by the gas."],["State the second law in terms of entropy.","The total entropy of an isolated system cannot decrease."],["Define entropy change for a reversible transfer.","ΔS = Qrev/T."],["State the maximum Carnot efficiency.","η = 1 - Tc/Th, using kelvin."],["Why can no heat engine be 100% efficient?","The second law requires some energy to be transferred to a colder reservoir."],
  ]);

  many("B.5 Current and circuits","SL",[
    ["Define electric current.","Rate of flow of charge: I = Δq/Δt."],["Define potential difference.","Energy transferred per unit charge: V = W/q."],["Define resistance.","R = V/I."],["State Ohm's law.","Current is proportional to potential difference when physical conditions such as temperature are constant."],["State electrical power in terms of V and I.","P = VI."],["How are currents related at a junction?","Total current entering equals total current leaving."],["How are potential differences related around a loop?","The algebraic sum is zero."],["What is emf?","Energy supplied per unit charge by a source."],["State the terminal-pd equation for a cell delivering current.","V = ε - Ir."],["How does resistance depend on resistivity?","R = ρL/A."],
  ]);
  [[6,3],[12,4],[9,0.5],[230,2],[5,0.02]].forEach(([V,I])=>add("B.5 Current and circuits","SL",`A component has ${V} V across it and current ${I} A. Calculate its resistance.`,`R = V/I = ${f(V/I)} Ω.`));

  many("C.1 Simple harmonic motion","SL",[
    ["Define simple harmonic motion.","Motion where acceleration is proportional to displacement and opposite in direction: a = -ω²x."],["Where is speed maximum in SHM?","At equilibrium."],["Where is acceleration magnitude maximum in SHM?","At maximum displacement."],["State the period-angular-frequency relation.","T = 2π/ω."],["State displacement as a function of time for one possible phase choice.","x = x₀ cos(ωt + φ)."],["How are acceleration and displacement phased in SHM?","They are 180° out of phase."],["How are velocity and displacement phased in SHM?","They are 90° out of phase."],["State the total energy of a mass-spring oscillator.","E = ½kA²."],["What is damping?","Loss of oscillation energy, causing amplitude to decrease."],["What is critical damping?","The minimum damping that returns a displaced system to equilibrium without oscillating."],
  ]);
  many("C.1 Simple harmonic motion","HL",[["State the period of a mass-spring system.","T = 2π√(m/k)."],["State the small-angle pendulum period.","T = 2π√(L/g)."],["What condition is required for the simple pendulum formula?","Small angular displacement so sin θ ≈ θ."]]);

  many("C.2 Wave model","SL",[
    ["Define wavelength.","Shortest distance between two points in phase."],["Define frequency.","Number of complete oscillations per unit time."],["State the wave equation.","v = fλ."],["Distinguish transverse and longitudinal waves.","Oscillations are perpendicular to propagation in transverse waves and parallel in longitudinal waves."],["What does wave intensity measure?","Power transferred per unit area."],["How does intensity vary with amplitude?","Intensity is proportional to amplitude squared."],["How does intensity from a point source vary with distance?","I = P/(4πr²), so it follows an inverse-square law."],["Define phase difference.","Difference in stage of oscillation, measured in radians or degrees."],["What phase difference corresponds to half a cycle?","π rad or 180°."],["Do particles in a mechanical wave travel with the wave?","No; they oscillate about equilibrium while energy propagates."],
  ]);
  [[2,3],[50,0.4],[3e8,6e14],[340,680],[1500,500]].forEach(([v,fq])=>add("C.2 Wave model","SL",`A wave travels at ${v} m s⁻¹ with frequency ${fq} Hz. Calculate its wavelength.`,`λ = v/f = ${f(v/fq)} m.`));

  many("C.3 Wave phenomena","SL",[
    ["State the law of reflection.","Angle of incidence equals angle of reflection."],["Define refractive index.","n = c/v for light in a medium."],["State Snell's law.","n₁ sin θ₁ = n₂ sin θ₂."],["What is total internal reflection?","Complete reflection when light travels from higher to lower refractive index above the critical angle."],["State the critical-angle relation for a medium to air.","sin c = 1/n."],["When is diffraction most noticeable?","When aperture or obstacle size is comparable to the wavelength."],["State conditions for two-source interference.","Sources must be coherent, with a constant phase difference and the same frequency."],["Condition for constructive interference in path difference?","Path difference = nλ."],["Condition for destructive interference in path difference?","Path difference = (n + ½)λ."],["What is polarization evidence for?","The transverse nature of a wave."],
  ]);
  many("C.3 Wave phenomena","HL",[["State the double-slit fringe-spacing relation.","s = λD/d."],["State the single-slit first-minimum condition.","b sin θ = λ."],["What does the Rayleigh criterion describe?","The minimum angular separation for two sources to be just resolved."]]);

  many("C.4 Standing waves and resonance","SL",[
    ["How is a standing wave formed?","By superposition of two waves of equal frequency and similar amplitude travelling in opposite directions."],["What is a node?","A point of zero displacement at all times."],["What is an antinode?","A point of maximum oscillation amplitude."],["What is the node-to-node separation?","λ/2."],["What is the node-to-adjacent-antinode separation?","λ/4."],["Define resonance.","Large-amplitude response when driving frequency is close to natural frequency."],["What determines the fundamental of a string fixed at both ends?","L = λ/2, so f = v/(2L)."],["What determines the fundamental of an open pipe?","L = λ/2."],["What determines the fundamental of a pipe closed at one end?","L = λ/4."],["How does damping affect a resonance curve?","It lowers and broadens the resonance peak."],
  ]);

  many("C.5 Doppler effect","SL",[
    ["What is the Doppler effect?","Observed frequency changes because of relative motion between source and observer."],["What happens to observed frequency as a source approaches?","It increases."],["What happens to observed wavelength ahead of an approaching source?","It decreases."],["Does the wave speed in the medium change because the source moves?","No."],["Give one use of the Doppler effect.","Examples include speed measurement, medical ultrasound, radar or astronomy."],["What causes cosmological redshift?","Expansion of space increases the observed wavelength of light from distant galaxies."],["What does a blueshift indicate?","Source and observer are moving towards each other."],["State the approximate Doppler relation for light at low recession speed.","Δf/f ≈ -v/c or Δλ/λ ≈ v/c."],
  ]);
  many("C.5 Doppler effect","HL",[["State the moving-source sound relation for a stationary observer.","f' = fv/(v ∓ us), with minus for approach."],["Why is a shock wave produced?","Wavefronts overlap when a source moves at or faster than wave speed."],["Define Mach number.","Source speed divided by wave speed."]]);

  many("D.1 Gravitational fields","SL",[
    ["Define gravitational field strength.","Force per unit mass: g = F/m."],["State Newton's law of gravitation.","F = Gm₁m₂/r²."],["What direction is a gravitational field?","Direction of force on a small test mass."],["State gravitational field strength outside a spherical mass.","g = GM/r² toward the centre."],["Define gravitational potential.","Work done per unit mass to bring a test mass from infinity: Vg = -GM/r."],["Why is gravitational potential negative?","Zero is at infinity and work must be supplied to escape the attractive field."],["State gravitational potential energy outside a spherical mass.","Ep = -GMm/r."],["What provides centripetal force for an orbiting satellite?","Gravity."],["State orbital speed for a circular orbit.","v = √(GM/r)."],["State escape speed from radius r.","vesc = √(2GM/r)."],
  ]);
  many("D.1 Gravitational fields","HL",[["State Kepler's third-law form for circular orbits.","T² = 4π²r³/(GM)."],["What is an equipotential surface?","A surface of constant potential; no work is done moving along it."],["How are field and potential related radially?","g = -dV/dr."]]);

  many("D.2 Electric and magnetic fields","SL",[
    ["Define electric field strength.","Force per unit positive test charge: E = F/q."],["State Coulomb's law.","F = kq₁q₂/r²."],["State electric field outside a point charge.","E = kQ/r²."],["Define electric potential.","Work done per unit charge bringing positive test charge from infinity: V = W/q."],["State electric potential due to a point charge.","V = kQ/r."],["State the uniform-field relation.","E = ΔV/d."],["State the force on a current-carrying wire in a magnetic field.","F = BIL sin θ."],["State the force on a moving charge in a magnetic field.","F = qvB sin θ."],["When is magnetic force on a moving charge zero?","When velocity is parallel or antiparallel to the field."],["Why does a magnetic force not change a particle's speed?","It is perpendicular to velocity and does no work."],
  ]);
  many("D.2 Electric and magnetic fields","HL",[["State magnetic field around a long straight wire.","B = μ₀I/(2πr)."],["State magnetic field inside a long solenoid.","B = μ₀nI."],["How are electric field and potential related?","E = -dV/dr in one dimension/radially."]]);

  many("D.3 Motion in electromagnetic fields","SL",[
    ["What path does a charged particle follow when entering a uniform magnetic field perpendicular to it?","A circular path."],["State the radius of a charged particle's circular path in B.","r = mv/(qB)."],["Does a magnetic field change a charged particle's kinetic energy?","No, because magnetic force does no work."],["How can an electric field accelerate a charged particle?","Electric force acts through a distance and transfers energy qΔV."],["State the energy gained by charge q through potential difference V.","ΔEₖ = qV."],["What is the velocity-selector condition for crossed E and B fields?","qE = qvB, so v = E/B."],["How does reversing charge sign affect deflection in a magnetic field?","It reverses the force and curvature direction."],["How does increasing momentum affect magnetic curvature at fixed q and B?","Radius increases because r = p/(qB)."],
  ]);
  many("D.3 Motion in electromagnetic fields","HL",[["State the cyclotron period for non-relativistic motion.","T = 2πm/(qB)."],["Why is cyclotron frequency independent of speed classically?","Both orbit radius and circumference grow in proportion to speed."],["What is the role of a mass spectrometer's magnetic field?","It separates ions according to mass-to-charge ratio."]]);

  many("D.4 Induction","HL",[
    ["Define magnetic flux.","Φ = BA cos θ through an area."],["Define magnetic flux linkage.","NΦ for a coil of N turns."],["State Faraday's law.","Induced emf equals the negative rate of change of flux linkage: ε = -N dΦ/dt."],["State Lenz's law.","Induced current acts to oppose the change that produced it."],["What does the negative sign in Faraday's law represent?","Lenz's law and conservation of energy."],["State the emf induced in a rod moving perpendicular to B.","ε = Bℓv."],["How does a transformer change voltage?","Vs/Vp = Ns/Np for an ideal transformer."],["State the ideal-transformer power relation.","VpIp = VsIs."],["Why is electricity transmitted at high voltage?","For the same power, current is smaller, reducing I²R losses."],["Define self-inductance.","Flux linkage per current; induced emf ε = -L dI/dt."],
  ]);

  many("E.1 Structure of the atom","SL",[
    ["What did Rutherford scattering reveal?","Atoms contain a tiny, dense, positively charged nucleus and are mostly empty space."],["What observation contradicted the plum-pudding model?","A small fraction of alpha particles were deflected through large angles."],["What is an emission spectrum?","Discrete wavelengths emitted when electrons move to lower energy levels."],["Why are atomic spectra discrete?","Electron energies are quantized."],["What does an absorption spectrum contain?","Dark lines where photons of specific energies were absorbed."],["State the photon-energy relation.","E = hf = hc/λ."],["What is ionization?","Removal of an electron from an atom."],["Define isotope.","Atoms of the same element with the same proton number but different neutron numbers."],["What is a nucleon?","A proton or neutron."],["Define mass number and atomic number.","Mass number A is nucleons; atomic number Z is protons."],
  ]);

  many("E.2 Quantum physics","HL",[
    ["State the photoelectric equation.","hf = Φ + Eₖ,max."],["Define work function.","Minimum energy needed to remove an electron from a surface."],["Define threshold frequency.","Minimum light frequency that causes photoemission: f₀ = Φ/h."],["What does increasing light intensity do above threshold?","It increases the photoelectron emission rate, not maximum kinetic energy."],["What does increasing frequency do above threshold?","It increases maximum photoelectron kinetic energy."],["State the de Broglie relation.","λ = h/p."],["What demonstrates electron wave behaviour?","Electron diffraction or interference."],["What does the wavefunction's squared magnitude represent?","Probability density for finding the particle."],["State Heisenberg's position-momentum uncertainty relation.","ΔxΔp ≥ ħ/2."],["What is quantum tunnelling?","A particle has a non-zero probability of crossing a classically forbidden barrier."],
  ]);

  many("E.3 Radioactive decay","SL",[
    ["What is radioactive decay?","Spontaneous and random transformation of an unstable nucleus."],["What is emitted in alpha decay?","A helium-4 nucleus."],["What changes in beta-minus decay?","A neutron becomes a proton, emitting an electron and antineutrino."],["What changes in beta-plus decay?","A proton becomes a neutron, emitting a positron and neutrino."],["What changes in gamma decay?","The nucleus loses energy; A and Z do not change."],["Define activity.","Decay rate: A = -dN/dt, measured in becquerels."],["State the radioactive decay law.","N = N₀e^(-λt), and A = A₀e^(-λt)."],["Relate half-life and decay constant.","T½ = ln 2/λ."],["Which radiation is most ionizing and least penetrating?","Alpha."],["Why is background count measured?","To subtract radiation not produced by the source."],
  ]);
  many("E.3 Radioactive decay","HL",[["Why is decay exponential?","Each nucleus has a constant probability of decay per unit time."],["What is the SI unit of decay constant?","s⁻¹."],["How is uncertainty in a count N estimated?","Approximately √N for random counting statistics."]]);

  many("E.4 Fission","SL",[
    ["What is nuclear fission?","A heavy nucleus splits into lighter nuclei, releasing energy and neutrons."],["What enables a fission chain reaction?","Neutrons released by one fission trigger further fissions."],["What is critical mass?","Minimum mass/configuration allowing a self-sustaining chain reaction."],["What is the role of a moderator?","It slows neutrons to increase the chance of further fission."],["What is the role of control rods?","They absorb neutrons to control the reaction rate."],["What is the role of coolant?","It transfers thermal energy from the reactor core."],["Why is energy released in fission?","Products have greater binding energy per nucleon and lower total mass."],["State mass-energy equivalence.","E = mc²."],["What is radioactive waste?","Unstable material produced or activated in nuclear processes that continues to emit radiation."],["Distinguish reactor and bomb chain reactions.","A reactor controls the rate; a weapon produces a rapid uncontrolled reaction."],
  ]);

  many("E.5 Fusion and stars","SL",[
    ["What is nuclear fusion?","Light nuclei combine into a heavier nucleus, releasing energy."],["Why does fusion require very high temperature?","Nuclei need enough kinetic energy to overcome electrostatic repulsion."],["What confines stars against expansion?","Inward gravity balances outward pressure in hydrostatic equilibrium."],["What powers main-sequence stars?","Fusion of hydrogen into helium."],["Why does fusion release energy for light nuclei?","The product has higher binding energy per nucleon and lower mass."],["What determines a main-sequence star's lifetime most strongly?","Its mass; massive stars use fuel much faster."],["What is stellar nucleosynthesis?","Production of heavier nuclei by reactions in stars."],["Where are many elements heavier than iron produced?","In neutron-capture events such as supernovae and neutron-star mergers."],["What is the main evidence for stellar composition?","Absorption and emission spectra."],["How is luminosity related to radius and temperature?","L = 4πR²σT⁴."],
  ]);
  many("E.5 Fusion and stars","HL",[["What is the Chandrasekhar limit?","Maximum mass of a stable white dwarf, about 1.4 solar masses."],["What supports a white dwarf?","Electron degeneracy pressure."],["What is the likely remnant of a very massive stellar core?","A neutron star or black hole, depending on mass."]]);

  many("Skills in physics","SL",[
    ["Define a random error.","An unpredictable variation that causes readings to scatter."],["Define a systematic error.","A consistent bias that shifts measurements in one direction."],["How can random error be reduced?","Repeat measurements and calculate a mean."],["Does repeating remove systematic error?","No."],["Define accuracy.","Closeness of a result to the accepted or true value."],["Define precision.","Closeness of repeated measurements to each other."],["Define uncertainty.","An estimate of the range within which the measured value is expected to lie."],["How is percentage uncertainty calculated?","Absolute uncertainty divided by measured value, multiplied by 100%."],["What is an outlier?","A result inconsistent with the pattern of the other data."],["What should be plotted on the x-axis?","The independent variable."],["What should be plotted on the y-axis?","The dependent variable."],["How is a graph gradient calculated?","Change in y divided by change in x using a large triangle."],["What do error bars show?","The uncertainty or variability associated with data points."],["When is a conclusion supported?","When it follows from the processed data within its uncertainties."],["What makes a hypothesis testable?","It predicts a measurable relationship between variables."],["Why are control variables held constant?","To isolate the effect of the independent variable."],["Distinguish repeatability and reproducibility.","Repeatability uses the same method/operator/equipment; reproducibility changes operator or equipment/location."],["What is a zero error?","An instrument reads a non-zero value when the true input is zero."],["How should analogue scale uncertainty usually be estimated?","About half the smallest scale division, unless repeated readings justify another estimate."],["How are uncertainties combined for multiplication or division?","Add fractional or percentage uncertainties."],["How are uncertainties combined for addition or subtraction?","Add absolute uncertainties."],["What is a line of best fit?","A line showing the overall trend with a balanced scatter of points."],["Why should a gradient triangle be large?","It reduces the percentage effect of reading uncertainties."],["What is interpolation?","Estimating within the measured data range."],["Why is extrapolation less reliable?","It assumes the trend continues beyond tested data."],
  ]);

  // Fresh numerical variants provide repeated equation practice without repeating a fixed paper question.
  [[120,15],[450,30],[72,6],[1000,40],[3.6,2]].forEach(([s,t])=>add("A.1 Kinematics","SL",`An object travels ${s} m in ${t} s at constant speed. Calculate its speed.`,`v = s/t = ${f(s/t)} m s⁻¹.`));
  [[4,6],[12,3],[0.5,20],[80,2],[1500,0.4]].forEach(([F,t])=>add("A.2 Forces and momentum","SL",`A constant force of ${F} N acts for ${t} s. Calculate the impulse.`,`J = FΔt = ${f(F*t)} N s.`));
  [[600,20],[1500,30],[72,6],[9000,45],[250,5]].forEach(([E,t])=>add("A.3 Work, energy and power","SL",`A device transfers ${E} J in ${t} s. Calculate its power.`,`P = E/t = ${f(E/t)} W.`));
  [[2,4],[0.5,12],[3,5],[1.2,20],[8,2]].forEach(([I,w])=>add("A.4 Rigid body mechanics","HL",`A body has moment of inertia ${I} kg m² and angular speed ${w} rad s⁻¹. Calculate its angular momentum.`,`L = Iω = ${f(I*w)} kg m² s⁻¹.`));
  [[0.6],[0.8],[0.9],[0.95],[0.5]].forEach(([b])=>add("A.5 Galilean and special relativity","HL",`Calculate the Lorentz factor for speed ${b}c.`,`γ = 1/√(1-${b}²) = ${f(1/Math.sqrt(1-b*b))}.`));
  [[0.2,334000],[0.5,2260000],[2,80000],[0.05,334000],[3,150000]].forEach(([m,L])=>add("B.1 Thermal energy transfers","SL",`Calculate the energy for a phase change of ${m} kg when L = ${L} J kg⁻¹.`,`Q = mL = ${f(m*L)} J.`));
  [[1,100,300],[2,50,400],[0.5,200,250],[3,80,350],[1.5,120,280]].forEach(([n,V,T])=>add("B.3 Gas laws","SL",`${n} mol of ideal gas is at ${T} K in volume ${V/1000} m³. Calculate pressure using R = 8.31 J mol⁻¹ K⁻¹.`,`p = nRT/V = ${f(n*8.31*T/(V/1000))} Pa.`));
  [[12,3],[24,2],[6,0.5],[230,5],[9,0.2]].forEach(([V,I])=>add("B.5 Current and circuits","SL",`Calculate electrical power when V = ${V} V and I = ${I} A.`,`P = VI = ${f(V*I)} W.`));
  [[2,0.8],[5,0.4],[10,0.25],[1.5,2],[20,0.1]].forEach(([T,A])=>add("C.1 Simple harmonic motion","SL",`An oscillator has period ${T} s and amplitude ${A} m. Calculate its angular frequency.`,`ω = 2π/T = ${f(2*Math.PI/T)} rad s⁻¹.`));
  [[0.5,4],[0.25,8],[2,3],[1.2,5],[0.1,20]].forEach(([l,fq])=>add("C.4 Standing waves and resonance","SL",`A string fixed at both ends has length ${l} m and fundamental frequency ${fq} Hz. Calculate wave speed.`,`v = fλ = f(2L) = ${f(2*l*fq)} m s⁻¹.`));
  [[2,5],[4,3],[10,0.5],[6,2],[8,1.5]].forEach(([q,V])=>add("D.3 Motion in electromagnetic fields","SL",`A charge of ${q} C moves through a potential difference of ${V} V. Calculate the energy gained.`,`ΔE = qV = ${f(q*V)} J.`));
  [[50,200,1000],[100,500,120],[240,60,25],[1000,250,12],[20,200,5]].forEach(([Np,Ns,Vp])=>add("D.4 Induction","HL",`An ideal transformer has Np = ${Np}, Ns = ${Ns}, and Vp = ${Vp} V. Calculate Vs.`,`Vs = Vp(Ns/Np) = ${f(Vp*Ns/Np)} V.`));
  [2,5,0.2,10,3].forEach((m)=>add("E.4 Fission","SL",`A mass defect of ${m} × 10⁻²⁸ kg occurs. Using c = 3.00 × 10⁸ m s⁻¹, calculate released energy.`,`E = Δmc² = ${f(m*9)} × 10⁻¹² J.`));
  [[100,5],[250,10],[80,4],[1200,30],[45,3]].forEach(([value,unc])=>add("Skills in physics","SL",`A measurement is ${value} ± ${unc}. Calculate its percentage uncertainty.`,`(${unc}/${value}) × 100 = ${f(unc/value*100)}%.`));

  window.IB_PHYSICS_DATA={topicMeta,questions};
})();
